In [1]:
import pandas as pd
import requests
print("Библиотеки установлены")

Библиотеки установлены

In [2]:
response = requests.get("https://dummyjson.com/products?limit=100")
print(response.status_code)

200

In [5]:
data = response.json()
print(type(data))
print(data.keys())

<class 'dict'>
dict_keys(['products', 'total', 'skip', 'limit'])

In [7]:
products = data["products"]
df = pd.DataFrame(products)
print(df.shape)
df.head(3)

(100, 22)

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,"{'width': 15.14, 'height': 13.08, 'depth': 22.99}",1 week warranty,Ships in 3-5 business days,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,"{'width': 9.26, 'height': 22.47, 'depth': 27.67}",1 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,"{'width': 29.27, 'height': 27.93, 'depth': 20.59}",3 months warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...

In [10]:
wanted = ['id','title','category','price','rating','stock']
products_df = df[wanted]

products_df.to_csv("../data/products_from_api.csv", index=False)
products_df.head()

   id                          title category  price  rating  stock
0   1  Essence Mascara Lash Princess   beauty   9.99    2.56     99
1   2  Eyeshadow Palette with Mirror   beauty  19.99    2.86     34
2   3                Powder Canister   beauty  14.99    4.64     89
3   4                   Red Lipstick   beauty  12.99    4.36     91
4   5                Red Nail Polish   beauty   8.99    4.32     79